apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
      - name: subscription-service
        image: your-docker-registry/subscription-service:latest
        ports:
        - containerPort: 3003
