apiVersion: v1
kind: Service
metadata:
  name: subscription-service
spec:
  selector:
    app: subscription-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: LoadBalancer
