apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
  labels:
    app: streaming-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      containers:
      - name: streaming-service
        image: paripuranam/streaming-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-frontend
  labels:
    app: streaming-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-frontend
  template:
    metadata:
      labels:
        app: streaming-frontend
    spec:
      containers:
      - name: streaming-frontend
        image: paripuranam/streaming-frontend:latest
        ports:
        - containerPort: 80
