pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = 'ac9cb270-d7f0-4b77-8b4d-1a9af0dfcddf'
        DOCKER_REGISTRY = 'paripuranam'
        IMAGE_VERSION = "v${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/paripuranam/ott-platform.git'
            }
        }

        stage('Build and Push Docker Images') {
            parallel {
                stage('Auth Service') {
                    steps {
                        script {
                            dockerImage = docker.build("${DOCKER_REGISTRY}/auth-service:${IMAGE_VERSION}", "./services/auth-service")
                            docker.withRegistry("https://${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS_ID}") {
                                dockerImage.push()
                            }
                        }
                    }
                }

                stage('Catalog Service') {
                    steps {
                        script {
                            dockerImage = docker.build("${DOCKER_REGISTRY}/catalog-service:${IMAGE_VERSION}", "./services/catalog-service")
                            docker.withRegistry("https://${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS_ID}") {
                                dockerImage.push()
                            }
                        }
                    }
                }

                stage('streaming service') {
                    steps {
                        script {
                            dockerImage = docker.build("${DOCKER_REGISTRY}/catalog-service:${IMAGE_VERSION}", "./services/streaming-service")
                            docker.withRegistry("https://${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS_ID}") {
                                dockerImage.push()
                            }
                        }
                    }
                }

                stage('subscription Service') {
                    steps {
                        script {
                            dockerImage = docker.build("${DOCKER_REGISTRY}/catalog-service:${IMAGE_VERSION}", "./services/subscription-service")
                            docker.withRegistry("https://${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS_ID}") {
                                dockerImage.push()
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
